#!/usr/bin/env bash
# shellcheck disable=SC2154 source=/dev/null
source "$(dirname "$0")"/../smash

test_dashes-in-test-function-names-works() {
    _exit_code=0
    true
}

test_--prefixed_function_names_work() {
    _exit_code=0
    true
}

run_tests "$@"
